### ISSUE TITLE
encrypt_password()

### ISSUE THREAD

**Issue by googley** [LPiner/mremoteng_password_decrypter#1]
Hi,

Do you know how to do the _**en**crypt_password()_ function?

Thanks in advance!

**Comment by LPiner** [comment]
https://github.com/LPiner/mremoteng_password_decrypter/blob/master/decrypt_password.py#L9

Put your password in there and then run it from the command line.

python decrypt_password.py

**Comment by googley** [comment]
No, I need to do the reverse process. I need a function that will encrypt a password like mRemoteNG do.
